### PR TITLE
bump bpaf + bikeshed

### PR DESCRIPTION
**Pull request by pacak**
Some changes to make it spark joy

When you pass correct parameters behavior should stay unchanged, but now `--help` becomes much more useful - user will know what the commands are, and if you replace `"add explanation here plox"` with something more concrete - it will also explain what to expect. Commands like `clean` and `update` no longer take test/filename, but this can be changed.

Ideally you should use `positional_os` and `PathBuf` to handle filenames but this requires more changes.

### CODE REVIEW

**Review by DhruvDh — APPROVED** [review]
Thanks a lot! I switched from fncmd to bpaf last minute so I did not have time to read the documentation properly; sorry about that. But thanks again!

**Comment by pacak** [comment]
I think this should deal with the conflict, but make sure to check :)

**Comment by pacak** [comment]
(and you have to merge it yourself)

**Comment by DhruvDh** [comment]
Yes, I was working on that. Just fixing some clippy lints and trying to allow TESTNAME to pass multiple names. Thanks again!

**Pull request merged**
